version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.11
jobs:
  build:
    docker:
      - image: circleci/node:12.9.1-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn lint:eslint

      - run: yarn test:staged

      - run: yarn build

      - aws-s3/sync:
          from: build
          to: "s3://multisig-tool/"
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
            overwrite: true
workflows:
  workflow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - multisig
