version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.11
jobs:
  build:
    docker:
      - image: circleci/node:12.9.1-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - node_modules

      - run: yarn lint:eslint

      - run: yarn test:staged

      - run: yarn build

      - aws-s3/sync:
          from: build
          to: "s3://multisig-tool/"
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
            overwrite: true
workflows:
  workflow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - multisig
